version: '3.10'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"


  app:

    build:
     context: .
     dockerfile: Dockerfile

    environment:
      HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: postgres
      PORT: 5432

    depends_on:
      - db
