# XPath
guest_log_in_button = "//button[text()='Guest log in']"
sign_in_button = "//button[text()='Sing in']"
sign_up_button = "//button[text()='Sing up']"
main_title_do_more = "//div[@class='hero-descriptor']/h1[text()='Do more!']"
text_title = "//p[text()='With the help of the Hillel auto project, you will have the opportunity to get hands-on experience in manual testing.']"
header_logo = "//a[@class='header_logo']"
icon_facebook = "//span[@class='socials_icon icon icon-facebook']"
icon_telegram = "//span[@class='socials_icon icon icon-telegram']"
icon_instagram = "//span[@class='socials_icon icon icon-instagram']"
icon_youtube = "//span[@class='socials_icon icon icon-youtube']"
icon_linkedin = "//span[@class='socials_icon icon icon-linkedin']"
sign_in_email = "//div[@class='form-group']//input[@id='signinEmail']"
sign_in_password = "//div[@class='form-group']//input[@id='signinPassword']"
about_title = "//div[@class='about-block']/p[@class='about-block_title h2'][1]"
about_image = "//div[@class='about-block_picture about-picture']/img[@class='about-picture_img'][1]"
button_create_new_car = "//button[contains(text()='Create new car')]"
alert_success = "//div[contains(@class, 'alert') and contains(text(), 'successfully')]"
nav_link_settings = "//nav//a[text()='Settings']"
car_card_mileage = "//div[contains(@class, 'garage-car')]//p[contains(text(), 'mileage')]"
input_brand = "//label[text()='Brand']/following-sibling::div//input"
input_model = "//label[text()='Model']/following-sibling::div//input"
button_submit_add = "//form//button[@type='submit' and contains(text()='Add')]"
registration_button = "//button[@class='btn btn-link' and text()='Registration']"
login_button = "//button[@class='btn btn-primary' and text()='Login']"
footer_title = "//h2[text()='Contacts']"

#CSS
button_sign_up = "button.hero-descriptor_btn.btn.btn-primary"
header_logo = "a.header_logo"
btn_guest = "button.header-link.-guest"
btn_sign_in = "button.btn.btn-outline-white.header_signin"
icon_facebook = "span.icon.icon-facebook"
icon_instagram = "span.icon.icon-instagram"
icon_linkedin = "span.icon.icon-linkedin"
icon_youtube = "span.icon.icon-youtube"
icon_telegram = "span.icon.icon-telegram"
sign_email = "#signinEmail"
sign_password = "#signinPassword"
remember = "#remember"
modal_content = "div.modal-content"
dropdown_user = "#userNavDropdown"
dropdown_menu_profil = "a.dropdown-item.btn.btn-link.user-nav_link[href='/panel/garage']"
dropdown_menu_profil = "a.dropdown-item.btn.btn-link.user-nav_link[href='/panel/expenses']"
dropdown_menu_profil = "a.dropdown-item.btn.btn-link.user-nav_link[href='/panel/instructions']"
dropdown_logout = "button.dropdown-item.btn btn-link.user-nav_link"
modal_conten = "div.modal-content"
add_brand_select = "#addCarBrand"
add_model_select = "#addCarModel"
add_mileag_select = "#addCarMileag"
add_expense_car = "#addExpenseCar"
add_expense_lirers = "#addExpenseLiters"
add_expense_total = "#addExpenseTotalCost"
